### ISSUE TITLE
writing readme for DASH

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/DASH#13]
make sure to add ;
- Images
- How to setup
- How to configure
- How to use

**Comment by crusader2000** [comment]
Hi
Can you expand a bit on this?

**Comment by 0xPrateek** [comment]
@crusader2000.. You can check my stardox repository https://gihtub.com/0xprateek/stardox 

- Adding images of web file uploader, terminal logs (you can stardox Gallery in readme.md)
- At the time of setup of DASH you need to add ngrok authtoken. I expect a `how to get ngrok authtoken` in the setup section.
- Writing about the configuration files. It's steps
- How to use section does not contain how to use dash using command-line arguments

**Comment by janish1999** [comment]
Hey, Is anyone working on this issue?? 
or can it be assigned to me?

**Comment by 0xPrateek** [comment]
@janish1999 Okay..! make sure that you update your progress through comments
